module sop_corba{
  
  interface GestionPacientes{
	struct pacienteDTO{
		string nombre;		
		string apellido;
		long numeroHabitacion;
		float edad;
	};
	
    boolean registrarPaciente(in pacienteDTO objPaciente);
   };
 };