package usuarios.sop_corba;


/**
* usuarios/sop_corba/GestionPacientesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from usuarios.idl
* jueves 7 de diciembre de 2023 12:31:02 AM COT
*/

public interface GestionPacientesOperations 
{
  boolean registrarPaciente (usuarios.sop_corba.GestionPacientesPackage.pacienteDTO objPaciente);
} // interface GestionPacientesOperations
