package usuarios.sop_corba;


/**
* usuarios/sop_corba/GestionPacientes.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from usuarios.idl
* jueves 7 de diciembre de 2023 12:31:02 AM COT
*/

public interface GestionPacientes extends GestionPacientesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionPacientes
