package servidorDeAlertas.sop_corba;


/**
* servidorDeAlertas/sop_corba/GestionPacientesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from alertas.idl
* viernes 8 de diciembre de 2023 12:29:24 AM COT
*/

public interface GestionPacientesOperations 
{
  servidorDeAlertas.sop_corba.GestionPacientesPackage.pacienteDTO buscarPaciente (int numeroHabitacion);
} // interface GestionPacientesOperations
