package servidorDeAlertas.sop_corba;


/**
* servidorDeAlertas/sop_corba/GestionPacientes.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from alertas.idl
* martes 12 de diciembre de 2023 02:57:02 AM COT
*/

public interface GestionPacientes extends GestionPacientesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionPacientes
