package servidorDeUsuarios.sop_corba;


/**
* servidorDeUsuarios/sop_corba/GestionPacientesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from usuarios.idl
* martes 12 de diciembre de 2023 02:56:10 AM COT
*/

public interface GestionPacientesOperations 
{
  boolean registrarPaciente (servidorDeUsuarios.sop_corba.GestionPacientesPackage.pacienteDTO objPaciente);
  servidorDeUsuarios.sop_corba.GestionPacientesPackage.pacienteDTO buscarPaciente (int numeroHabitacion);
} // interface GestionPacientesOperations
